#!/usr/bin/env node
/**
 * Performance Test Seed Script
 *
 * Creates 500 tasks across multiple categories in a workspace for performance testing.
 * Usage: node scripts/seedPerformanceData.js <workspace_id> <user_id>
 *
 * Example: node scripts/seedPerformanceData.js ws-uuid-123 1
 */

require('dotenv').config();
const { getClient } = require('../config/database');

const TASK_COUNT = 500;
const CATEGORY_COUNT = 8;
const PRIORITIES = ['low', 'medium', 'high', 'urgent'];
const STATUSES = ['todo', 'in_progress', 'completed'];

const CATEGORY_NAMES = [
  'Backlog', 'To Do', 'In Progress', 'Review',
  'Design', 'Development', 'Testing', 'Done',
];

const TASK_TITLES = [
  'Update user authentication flow',
  'Fix pagination on search results',
  'Add dark mode support',
  'Optimize database queries',
  'Write API documentation',
  'Implement file upload feature',
  'Refactor notification system',
  'Add export to CSV functionality',
  'Fix mobile responsive layout',
  'Implement drag and drop reordering',
  'Add email verification reminder',
  'Update password complexity rules',
  'Create admin dashboard',
  'Fix timezone handling',
  'Add bulk task operations',
  'Implement task templates',
  'Update onboarding flow',
  'Fix memory leak in list view',
  'Add keyboard shortcuts',
  'Implement real-time notifications',
];

async function seed(workspaceId, userId) {
  const client = await getClient();

  try {
    await client.query('BEGIN');

    // Create categories
    const categoryIds = [];
    for (let i = 0; i < CATEGORY_COUNT; i++) {
      const result = await client.query(
        `INSERT INTO categories (name, color, position, created_by, workspace_id)
         VALUES ($1, $2, $3, $4, $5) RETURNING id`,
        [
          `${CATEGORY_NAMES[i]} (perf)`,
          `#${Math.floor(Math.random() * 16777215).toString(16).padStart(6, '0')}`,
          i,
          userId,
          workspaceId,
        ]
      );
      categoryIds.push(result.rows[0].id);
    }

    console.log(`Created ${categoryIds.length} categories`);

    // Create tasks
    for (let i = 0; i < TASK_COUNT; i++) {
      const categoryId = categoryIds[i % CATEGORY_COUNT];
      const position = Math.floor(i / CATEGORY_COUNT);
      const priority = PRIORITIES[Math.floor(Math.random() * PRIORITIES.length)];
      const status = STATUSES[Math.floor(Math.random() * STATUSES.length)];
      const title = TASK_TITLES[i % TASK_TITLES.length];
      const dueDate = new Date();
      dueDate.setDate(dueDate.getDate() + Math.floor(Math.random() * 60) - 15);

      await client.query(
        `INSERT INTO tasks (title, description, category_id, priority, status, due_date, position, created_by, workspace_id, completed_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)`,
        [
          `${title} #${i + 1}`,
          `Performance test task ${i + 1}. This task was generated by the seed script for load testing with ${TASK_COUNT} tasks.`,
          categoryId,
          priority,
          status,
          dueDate.toISOString(),
          position,
          userId,
          workspaceId,
          status === 'completed' ? new Date().toISOString() : null,
        ]
      );

      if ((i + 1) % 100 === 0) {
        console.log(`Created ${i + 1}/${TASK_COUNT} tasks...`);
      }
    }

    await client.query('COMMIT');
    console.log(`\nDone! Created ${CATEGORY_COUNT} categories and ${TASK_COUNT} tasks in workspace ${workspaceId}`);
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('Seed failed:', err.message);
    process.exit(1);
  } finally {
    client.release();
    process.exit(0);
  }
}

const workspaceId = process.argv[2];
const userId = process.argv[3];

if (!workspaceId || !userId) {
  console.error('Usage: node scripts/seedPerformanceData.js <workspace_id> <user_id>');
  process.exit(1);
}

seed(workspaceId, parseInt(userId, 10));
